# Autogenerated wrapper script for libbensolve_jll for x86_64-w64-mingw32
export libbensolve

using GLPK_jll
JLLWrappers.@generate_wrapper_header("libbensolve")
JLLWrappers.@declare_library_product(libbensolve, "libbensolve.dll")
function __init__()
    JLLWrappers.@generate_init_header(GLPK_jll)
    JLLWrappers.@init_library_product(
        libbensolve,
        "bin\\libbensolve.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
