# Autogenerated wrapper script for libbensolve_jll for x86_64-linux-musl
export libbensolve

using GLPK_jll
JLLWrappers.@generate_wrapper_header("libbensolve")
JLLWrappers.@declare_library_product(libbensolve, "libbensolve.so")
function __init__()
    JLLWrappers.@generate_init_header(GLPK_jll)
    JLLWrappers.@init_library_product(
        libbensolve,
        "lib/libbensolve.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
