# Autogenerated wrapper script for libbensolve_jll for x86_64-apple-darwin
export libbensolve

using GLPK_jll
JLLWrappers.@generate_wrapper_header("libbensolve")
JLLWrappers.@declare_library_product(libbensolve, "@rpath/libbensolve.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GLPK_jll)
    JLLWrappers.@init_library_product(
        libbensolve,
        "lib/libbensolve.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
